---
- hosts: "{{ servidores }}"
  become: true
  tasks:
  - name: crear el directorio prueba_when
    file:
      path: /var/tmp/prueba_when
      state: directory
    when: servidores == "192.168.17.105"
