---
- hosts: "{{ servidores }}"
  gather_facts: false
  become: true
  tasks:
  - name: instalar Apache
    package:
      name: httpd
      state: present
    tags: install
  - name: iniciamos httpd y lo mantenemos persistente al reboot
    service:
      name: httpd
      state: started
      enabled: yes
    tags: config
  - name: creamos pagina de bienvenida
    copy:
      dest: /var/www/html/index.html
      content: |
        <html>
          <body>
            <h1>HOLA MUNDO</h1>
            <p>FUNCIONO</p>
          </body>
        </html>
    tags: config
  - name: desinstalar Apache
    package:
      name: httpd
      state: absent
    tags: [uninstall, never]
