---
- hosts: "{{ servidores }}"
  become: true
  tasks:
  - name: crear usuario
    user:
      name: "{{ item.usuario }}"
      groups: "{{ item.grupo }}"
      shell: "/bin/bash"
      comment: "hola Pepe"
      state: present
    with_items:
    - { usuario: 'Pepe', grupo: 'tsysadm' }
    - { usuario: 'Mari', grupo: 'wheel' }
    - { usuario: 'Paco', grupo: 'wheel' }
    - { usuario: 'Lola', grupo: 'wheel' }
